# -*- coding: utf-8 -*-
"""ZaidTaiyab_Initial_Contribution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-DdIgB-vIDDiAwn5Bdr8uuM5ode-r1N
"""

import os, json, textwrap, re, time
import requests

API_KEY  = os.getenv("OPENAI_API_KEY", "")
API_BASE = os.getenv("API_BASE", "https://openai.rc.asu.edu/v1")
MODEL    = os.getenv("MODEL_NAME", "qwen3-30b-a3b-instruct-2507")

def call_model_chat_completions(prompt: str,
                                system: str = "You are a helpful assistant. Reply with only the final answer—no explanation.",
                                model: str = MODEL,
                                temperature: float = 0.0,
                                timeout: int = 60) -> dict:
    """
    Calls an OpenAI-style /v1/chat/completions endpoint and returns:
    { 'ok': bool, 'text': str or None, 'raw': dict or None, 'status': int, 'error': str or None, 'headers': dict }
    """
    url = f"{API_BASE}/chat/completions"
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type":  "application/json",
    }
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user",   "content": prompt}
        ],
        "temperature": temperature,
        "max_tokens": 512,
    }

    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=timeout)
        status = resp.status_code
        hdrs   = dict(resp.headers)
        if status == 200:
            data = resp.json()
            text = data.get("choices", [{}])[0].get("message", {}).get("content", "")
            return {"ok": True, "text": text, "raw": data, "status": status, "error": None, "headers": hdrs}
        else:
            # try best-effort to surface error text
            err_text = None
            try:
                err_text = resp.json()
            except Exception:
                err_text = resp.text
            return {"ok": False, "text": None, "raw": None, "status": status, "error": str(err_text), "headers": hdrs}
    except requests.RequestException as e:
        return {"ok": False, "text": None, "raw": None, "status": -1, "error": str(e), "headers": {}}

def analogical_reasoning_agent(prompt, return_trace=False):
    system_prompt = """You are a careful analogical reasoning agent. You will solve new problems by recalling similar problems that you have seen
    before and using their structure and adapting the strcuture to the new problem.

You must solve problems by recalling relevant exemplars.

You must follow this exact format at each step:

Thought: Recall Relevant Exemplars, and pick the exemplar that is the most similar, then get the relevant elements of the chosen exemplar.
Identify the values, structure, steps, relationships and every other relevant element.

Adapt: Adapt the structure of the recalled exemplar to the new problem, and carefully solve the problem. Verfiy the answer, and if new problem is not solved or it is too different,
pick another similar exemplar and go to the thought line and repeat.

Rules:
- Always recall exemplars
- Do not skip the Thought line
- Do not skip the Adapt line
- When you are certain, output Final Answer: <answer>
- The answer inside Final Answer: <anwser> must be short and contain only the answer
"""

    result = call_model_chat_completions(
            prompt=prompt,
            system=system_prompt,
            temperature=0.0,
            timeout=30
        )

    text = (result.get("text") or "").strip()

    # 2 retries
    if not text:
        retry = call_model_chat_completions(
            prompt=prompt,
            system=system_prompt,
            temperature=0.0,
            timeout=30
        )
        text = (retry.get("text") or "").strip()

    if not text:
        retry = call_model_chat_completions(
            prompt=prompt,
            system=system_prompt,
            temperature=0.0,
            timeout=30
        )
        text = (retry.get("text") or "").strip()

    if return_trace:
        match = re.search(r"Final Answer:\s*(.+)", text, flags=re.IGNORECASE)
        extracted = match.group(1).strip() if match else text
        return {
            "raw_output": text,
            "candidate_final_answer": extracted
        }

    return text

coding_results_analogical = []
i = 0
for idx,domain in enumerate((data)):
    i += 1
    if i > 1000:
        break
    if domain.get("domain")!= "coding":
        continue
    else:
        pred=analogical_reasoning_agent(domain["input"])
        correct = grade_exact(pred,domain["output"])
        coding_results_analogical.append({"index":idx,"pred":pred,"correct":correct})

correct_num = sum(r["correct"] for r in coding_results_analogical)
total=len(coding_results_analogical)

print(correct_num/len(coding_results_analogical))

def tree_of_thought_reasoning_agent(n, problem, return_trace=False):
        prompt = f"""Think step by Step
        Final Answer: <answer only>

        Rules:
        - Generate {n} paths
        - Pick most accurate path at each step
        - Put the final answer on its own line starting with exactly: Final Answer:

        Problem: {problem}
        """

        result = call_model_chat_completions(
            prompt=prompt,
            system="You are a careful mathematical reasoning assistant. Keep reasoning brief and end with exactly 'Final Answer: <answer only>'.",
            temperature=0.0,
            timeout=30
        )

        text = (result.get("text") or "").strip()

        if not text:
            retry = call_model_chat_completions(
                prompt=prompt,
                system="Return brief reasoning and end with exactly 'Final Answer: <answer only>'.",
                temperature=0.0,
                timeout=30
            )
            text = (retry.get("text") or "").strip()

        if return_trace:
            match = re.search(r"Final Answer:\s*(.+)", text, flags=re.IGNORECASE)
            extracted = match.group(1).strip() if match else text
            return {
                "raw_output": text,
                "candidate_final_answer": extracted
            }

        return text

def zero_shot_chain_of_thought_reasoning_agent(problem, return_trace=False):
        prompt = f"""Think step by Step
        Final Answer: <answer only>

        Rules:
        - Keep reasoning concise
        - Think step by step
        - Put the final answer on its own line starting with exactly: Final Answer:

        Problem: {problem}
        """

        result = call_model_chat_completions(
            prompt=prompt,
            system="You are a careful mathematical reasoning assistant. Keep reasoning brief and end with exactly 'Final Answer: <answer only>'.",
            temperature=0.0,
            timeout=30
        )

        text = (result.get("text") or "").strip()

        if not text:
            retry = call_model_chat_completions(
                prompt=prompt,
                system="Return brief reasoning and end with exactly 'Final Answer: <answer only>'.",
                temperature=0.0,
                timeout=30
            )
            text = (retry.get("text") or "").strip()

        if return_trace:
            match = re.search(r"Final Answer:\s*(.+)", text, flags=re.IGNORECASE)
            extracted = match.group(1).strip() if match else text
            return {
                "raw_output": text,
                "candidate_final_answer": extracted
            }

        return text